Repository Marius-P1/Survivor-Pool, pull requests merged in 2024-09, with the labels that each got.

#3 Create contributing and mirroring
  .github/workflows/mirror.yml
  Contributing.md
Labels: enhancement

#8 Setup the project backend
  backend/.gitignore
  backend/index.ts
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/tsconfig.json
Labels: enhancement

#10 Add issue template for bug and features
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#12 Add login route for the backend
  backend/.gitignore
  backend/controllers/user.ts
  backend/index.ts
Labels: enhancement

#14 Implement a middleware for authentication handling
  backend/index.ts
  backend/middleware/auth.ts
Labels: enhancement

#17 Setup the frontend
  frontend/.browserslistrc
  frontend/.eslintrc.js
  frontend/README.md
  frontend/babel.config.js
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/assets/main.css
  frontend/src/components/AppHeader.vue
  frontend/src/components/AppSidebar.vue
  frontend/src/main.ts
  frontend/src/pages/AppAstrological.vue
  frontend/src/pages/AppHome.vue
  frontend/src/pages/AppProfile.vue
  frontend/src/pages/AppWardrobe.vue
  frontend/src/pages/master/AppDashboard.vue
  frontend/src/pages/master/AppLogin.vue
  frontend/src/router/index.ts
  frontend/src/shims-vue.d.ts
  frontend/tsconfig.json
  frontend/vue.config.js
Labels: enhancement

#20 Automate data fetch between old and new databases
  backend/controllers/user.ts
  backend/fetch/fetch.ts
  backend/fetch/fetchClothes.ts
  backend/fetch/fetchCustomers.ts
  backend/fetch/fetchEncounters.ts
  backend/fetch/fetchEvents.ts
  backend/fetch/fetchTips.ts
  backend/index.ts
  backend/prisma/schema.prisma
Labels: enhancement

#16 Create function to fetch databases
  backend/fetch/fetch.ts
  backend/fetch/fetchEmployees.ts
  backend/index.ts
  backend/prisma/schema.prisma
Labels: enhancement

#27 Create API routes to get customers informations
  backend/controllers/customers.ts
  backend/dto/customersDTO.ts
  backend/fetch/fetch.ts
  backend/fetch/fetchClothes.ts
  backend/fetch/fetchCustomers.ts
  backend/index.ts
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  frontend/.gitignore
Labels: enhancement

#24 Create routes for get the employees informations
  backend/fetch/fetchEmployees.ts
  backend/index.ts
  backend/prisma/schema.prisma
  backend/routes/employee.ts
Labels: enhancement

#31 Create option to add customer to coach
  backend/prisma/schema.prisma
  backend/routes/employee.ts
Labels: enhancement

#37 Create employee page with client assignment feature
  backend/fetch/fetchEmployees.ts
  frontend/src/main.ts
  frontend/src/pages/AppEmployees.vue
  frontend/src/router/index.ts
Labels: enhancement

#35 Create the wardrobe page
  frontend/src/pages/AppWardrobe.vue
Labels: enhancement

#38 33 create tips route
  .gitignore
  backend/fetch/fetchEmployees.ts
  backend/index.ts
  backend/prisma/schema.prisma
  backend/routes/tips.ts
Labels: enhancement

#39 34 create route for events
  backend/index.ts
  backend/routes/event.ts
Labels: enhancement

#36 Make the astrological frontend page
  backend/index.ts
  frontend/.gitignore
  frontend/src/assets/default-avatar.jpg
  frontend/src/assets/main.css
  frontend/src/assets/zodiac_compatibility_pairs.json
  frontend/src/components/AppHeader.vue
  frontend/src/main.ts
  frontend/src/pages/AppAstrological.vue
  frontend/src/pages/AppWardrobe.vue
  frontend/src/pages/master/AppLogin.vue
Labels: enhancement

#44 Create tips page
  frontend/src/pages/AppTips.vue
  frontend/src/router/index.ts
Labels: enhancement

#48 Create a home page with company statistics
  frontend/src/pages/AppHome.vue
  frontend/src/pages/AppWardrobe.vue
Labels: enhancement

#51 Create global header tab menu for website
  frontend/src/App.vue
  frontend/src/assets/main.css
  frontend/src/assets/usa.png
  frontend/src/components/AppHeader.vue
  frontend/src/components/AppSidebar.vue
  frontend/src/main.ts
  frontend/src/pages/AppEmployees.vue
  frontend/src/pages/master/AppDashboard.vue
  frontend/src/router/index.ts
Labels: enhancement

#55 Secure frontend pages with authentication
  backend/controllers/customers.ts
  backend/controllers/user.ts
  backend/index.ts
  backend/middleware/managerAuth.ts
  backend/routes/customers.ts
  backend/routes/employee.ts
  backend/routes/event.ts
  backend/routes/statistics.ts
  backend/routes/tips.ts
  backend/routes/token.ts
  frontend/.gitignore
  frontend/src/App.vue
  frontend/src/components/AppHeader.vue
  frontend/src/pages/AppAstrological.vue
  frontend/src/pages/AppCustomers.vue
  frontend/src/pages/AppEmployees.vue
  frontend/src/pages/AppHome.vue
  frontend/src/pages/AppTips.vue
  frontend/src/pages/AppWardrobe.vue
  frontend/src/pages/master/AppLogin.vue
  frontend/src/services/TokenService.ts
Labels: enhancement

#53 Create an event page
  frontend/package.json
  frontend/src/assets/temporary_map.jpg
  frontend/src/pages/AppEvents.vue
  frontend/src/router/index.ts
Labels: enhancement

#63 Create cicd release system
  .github/workflows/Release.yml
  backend/package-lock.json
  backend/package.json
  frontend/.gitignore
Labels: enhancement

#60 Update the tips page according to the new mock up
  frontend/src/main.ts
  frontend/src/pages/AppTips.vue
Labels: enhancement

#64 Fix cicd release
  .github/workflows/Release.yml
Labels: bug

#65 Update website styling to match new design mockups
  backend/routes/employee.ts
  backend/routes/token.ts
  frontend/src/components/AppHeader.vue
  frontend/src/pages/AppAstrological.vue
  frontend/src/pages/AppCustomers.vue
  frontend/src/pages/AppEmployees.vue
  frontend/src/pages/AppEvents.vue
  frontend/src/pages/AppWardrobe.vue
Labels: enhancement

#66 Fix cicd release
  .github/workflows/Release.yml
Labels: bug

#68 Update the dashboard page according to the new mock up
  frontend/package.json
  frontend/src/main.ts
  frontend/src/pages/AppHome.vue
  frontend/src/pages/AppProfile.vue
  frontend/src/router/index.ts
Labels: enhancement

#69 Fix ci
  .github/workflows/Release.yml
Labels: bug, enhancement

#70 Fix cicd Release
  .github/workflows/Release.yml
Labels: bug

#72 Remove back build
  .github/workflows/Release.yml
Labels: bug

#73 Get meeting by employee
  backend/routes/employee.ts
Labels: enhancement

#71 Make the statistics frontend page
  frontend/src/main.ts
  frontend/src/pages/AppCustomers.vue
  frontend/src/pages/AppStatistics.vue
  frontend/src/router/index.ts
Labels: enhancement

#74 Update customer search layout
  frontend/src/pages/AppCustomers.vue
Labels: enhancement
